#Variables d'environnement pour la configuration de l'application
spring.application.name=baticonnecte

#spring.datasource.url=jdbc:postgresql://localhost:5432/baticonnecte_db
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://ep-tiny-rice-aqbpntco.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wGbqk1YROvd0
pring.datasource.driver-class-name=org.postgresql.Driver


cloudinary.cloud-name=dzy2jjnlo
cloudinary.api-key=493879157578295
cloudinary.api-secret=kIkNDTiGM7ATGV5HdziFzN6mYBE

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

JWT_SECRET=J5mzMk0gsJnXNVeNT49HhTrZbr17Vom3
JWT_EXPIRATION=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#server.port=8096
server.port=8090