#Variables d'environnement pour la configuration de l'application
spring.application.name=baticonnecte
spring.datasource.url=jdbc:postgresql://localhost:5432/baticonnecte_db
spring.datasource.username=postgres
spring.datasource.password=Postgres@1234

spring.datasource.driver-class-name=org.postgresql.Driver

JWT_SECRET=sk2YlYiOdhQNp28ZxgCrWqJtlpmE99lGJs2zQanUzaoQQCDusERQe3iWNEEY5qag6YgHhzPMUXrFSyj5SjfIXD
JWT_EXPIRATION=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8090